[controlplane]
mimir-control ansible_host=172.16.9.105

[workers]
mimir-worker1 ansible_host=172.16.9.102
mimir-worker2 ansible_host=172.16.9.103
mimir-worker3 ansible_host=172.16.9.104

[k8s:children]
controlplane
workers
